### ISSUE TITLE
Read root path from configuration

### ISSUE THREAD

**Issue by Vadi** [bertramdev/ratpack-asset-pipeline#1]
I am [refering this line](https://github.com/bertramdev/ratpack-asset-pipeline/blob/master/src/main/java/asset/pipeline/ratpack/AssetPipelineService.java#L45) from `AssetPipelineService`. Why it is neccessary to hardcode the base path (like this  `../assets`)? In a multi-module gradle setup, a web project is just one inner module and it is normal tendency to keep all static files inside a web project folder.

I can provide a PR if neccessary. Thanks.

**Comment by davydotcom** [comment]
This equates to src/assets and is kept out of the ratpack folder so it does not get processed as a simple ProcessResource task

**Comment by Vadi** [comment]
I don't think it gets src/assets in multimodule project

```
<root>
    *assets*
    lib-project
    web-project
      src
        main
           ...
```

The folder structure has to be like this for current implementation to work. This seems like an unnecessary assumption

Based on current implementation the `assets` folder has to be in root because you're adding `../assets` in the mentioned line of code. Does it necessary?

**Comment by davydotcom** [comment]
This is to get it relative to rat pack home which is typically where the `.ratpack` file is in `src/ratpack`

## so assets is normally in `src/assets`

David Estes

On July 2, 2015 at 2:18:46 PM, Vadi Kumar (notifications@github.com) wrote:

I don't think it gets src/assets in multimodule project

<root>
    assets
    lib-project
    web-project
      src
        main
           ...

Based on current implementation the assets folder has to be in root because you're adding ../assets in the mentioned line of code. Does it neccessary?

**Comment by Vadi** [comment]
With no configuration change below structure is not working for me ..

```
<root>
 |- lib-project
 |- web-project
 |---.ratpack
 |---src
 |----assets
```

`.ratpack` file is in web-project folder.

**Comment by davydotcom** [comment]
Very odd project structure here can maybe make the base path configurable at launch

**Comment by Vadi** [comment]
I will follow the base path configuration approach. Thanks for the help.
